version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  aws-sagemaker: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  testing-setup-command:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - aws-sagemaker/setup
      - run:
          name: Verify aws-sagemaker/setup
          command: which cci-sagemaker
workflows:
  test-deploy:
    jobs:
      - testing-setup-command:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/aws-sagemaker
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - testing-setup-command
          context: Circleci-Ai-Orb-Publishing
          filters: *release-filters
